### ISSUE TITLE
关于emby观影报告使用问题

### ISSUE THREAD

**Issue by autunn** [thsrite/MoviePilot-Plugins#10]
我的emby是在docker下安装的，没有在config目录找到/data/EmbyReporter/rss/这个目录，然后手动创建了一个，并且做了映射，但是在启用的时候报错了，希望大佬指点下
日志
ERROR:   base.py - Job "Emby观影报告 (trigger: date[2024-01-13 03:00:36 CST], nex
t run at: 2024-01-13 03:00:36 CST)" raised an exception                          
Traceback (most recent call last):                                               
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", l
ine 125, in run_job                                                              
    retval = job.func(*job.args, **job.kwargs)                                   
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
  File "/app/app/plugins/embyreporter/__init__.py", line 150, in __report        
    report_path = self.draw(res_path=self._res_dir,                              
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
  File "/app/app/plugins/embyreporter/__init__.py", line 546, in draw            
    bg_list = os.listdir(bg_path)                                                
              ^^^^^^^^^^^^^^^^^^^                                                
FileNotFoundError: [Errno 2] No such file or directory: '/config/plugins/EmbyRepo
rter/bg'

**Comment by thsrite** [comment]
教程文档说的很清楚，把插件库的文件下载到你本地映射到mp
