### ISSUE TITLE
moviePilotv2 手动操作运行一次 一直报错

### ISSUE THREAD

**Issue by dengboyun** [thsrite/MoviePilot-Plugins#103]
###  一直不断的报错
loudlinkmonitor - 目录监控发生错误：ChainBase.transfer() got an unexpected keyword argument 'target_directory' - Traceback (most recent call last):

**部分日志：**
    transferinfo: TransferInfo = self.chain.transfer(fileitem=file_item,
  File "/app/app/plugins/cloudlinkmonitor/__init__.py", line 428, in __handle_file
【ERROR】2024-11-03 00:44:16,206 - cloudlinkmonitor - 目录监控发生错误：ChainBase.transfer() got an unexpected keyword argument 'target_directory' - Traceback (most recent call last):
【INFO】2024-11-03 00:44:16,204 - cloudlinkmonitor - Deadpool.and.Wolverine.2024.V2.2160p.iT.WEB-DL.H265.DV.DDP5.1.Atmos-ADWeb.mkv 识别为：电影 死侍与金刚狼 (2024)
【INFO】2024-11-03 00:44:16,202 - themoviedb - Deadpool And Wolverine TMDB识别结果：电影 死侍与金刚狼 (2024) 533535
【INFO】2024-11-03 00:44:15,844 - themoviedb - Deadpool And Wolverine 使用TMDB识别缓存：死侍与金刚狼
【INFO】2024-11-03 00:44:15,822 - cloudlinkmonitor - 开始处理文件 /downloads/movie/Deadpool.and.Wolverine.2024.V2.2160p.iT.WEB-DL.H265.DV.DDP5.1.Atmos-ADWeb/Deadpool.and.Wolverine.2024.V2.2160p.iT.WEB-DL.H265.DV.DDP5.1.Atmos-ADWeb.mkv ...

TypeError: ChainBase.transfer() got an unexpected keyword argument 'target_directory'
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    transferinfo: TransferInfo = self.chain.transfer(fileitem=file_item,
  File "/app/app/plugins/cloudlinkmonitor/__init__.py", line 428, in __handle_file
【ERROR】2024-11-03 00:44:15,821 - cloudlinkmonitor - 目录监控发生错误：ChainBase.transfer() got an unexpected keyword argument 'target_directory' - Traceback (most recent call last):
【INFO】2024-11-03 00:44:15,819 - cloudlinkmonitor - Murder.on.the.Orient.Express.1974.UHD.BluRay.2160p.2Audio.DTS-HD.MA.5.1.x265.10bit.HDR-beAst.mkv 识别为：电影 东方快车谋杀案 (1974)
【INFO】2024-11-03 00:44:15,817 - themoviedb - Murder On The Orient Express TMDB识别结果：电影 东方快车谋杀案 (1974) 4176
【INFO】2024-11-03 00:44:15,660 - themoviedb - Murder On The Orient Express 使用TMDB识别缓存：东方快车谋杀案
【INFO】2024-11-03 00:44:15,635 - cloudlinkmonitor - 开始处理文件 /downloads/movie/Murder.on.the.Orient.Express.1974.UHD.BluRay.2160p.2Audio.DTS-HD.MA.5.1.x265.10bit.HDR-beAst/Murder.on.the.Orient.Express.1974.UHD.BluRay.2160p.2Audio.DTS-HD.MA.5.1.x265.10bit.HDR-beAst.mkv ...

TypeError: ChainBase.transfer() got an unexpected keyword argument 'target_directory'
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    transferinfo: TransferInfo = self.chain.transfer(fileitem=file_item,
  File "/app/app/plugins/cloudlinkmonitor/__init__.py", line 428, in __handle_file
【ERROR】2024-11-03 00:44:15,633 - cloudlinkmonitor - 目录监控发生错误：ChainBase.transfer() got an unexpected keyword argument 'target_directory' - Traceback (most recent call last):
【INFO】2024-11-03 00:44:15,630 - cloudlinkmonitor - Our.Little.Sister.2015.KOR.UHD.BluRay.2160p.10bit.DoVi.DTS-HD.MA.5.1.x265-beAst.mkv 识别为：电影 海街日记 (2015)
【INFO】2024-11-03 00:44:15,628 - themoviedb - Our Little Sister TMDB识别结果：电影 海街日记 (2015) 315846
【INFO】2024-11-03 00:44:15,173 - themoviedb - Our Little Sister 使用TMDB识别缓存：海街日记
【INFO】2024-11-03 00:44:15,149 - cloudlinkmonitor - 开始处理文件 /downloads/movie/Our.Little.Sister.2015.KOR.UHD.BluRay.2160p.10bit.DoVi.DTS-HD.MA.5.1.x265-beAst/Our.Little.Sister.2015.KOR.UHD.BluRay.2160p.10bit.DoVi.DTS-HD.MA.5.1.x265-beAst.mkv ...

TypeError: ChainBase.transfer() got an unexpected keyword argument 'target_directory'

**Comment by thsrite** [comment]
更新最新mp v2，插件卸载掉重装试试。我没遇到这个问题
