### ISSUE TITLE
文件转移模块运行失败

### ISSUE THREAD

**Issue by WiKiBIRD** [thsrite/MoviePilot-Plugins#153]
ERROR】2024-11-26 07:44:25,083 - cloudlinkmonitor - 文件转移模块运行失败

TypeError: expected str, bytes or os.PathLike object, not NoneType
        ^^^^^^^^^^^^
    a = os.fspath(a)
  File "/usr/local/lib/python3.11/pathlib.py", line 493, in _parse_args
                       ^^^^^^^^^^^^^^^^^^^^^^
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.11/pathlib.py", line 509, in _from_parts
           ^^^^^^^^^^^^^^^^^^^^^
    self = cls._from_parts(args)
  File "/usr/local/lib/python3.11/pathlib.py", line 871, in __new__
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    library_dir = Path(target_dir.library_path)
  File "/app/app/modules/filemanager/__init__.py", line 877, in __get_dest_dir
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    target_path = self.__get_dest_dir(mediainfo=mediainfo, target_dir=target_directory,
  File "/app/app/modules/filemanager/__init__.py", line 373, in transfer
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 112, in run_module
Traceback (most recent call last):
【ERROR】2024-11-26 07:44:25,076 - chain - 运行模块 FileManagerModule.transfer 出错：expected str, bytes or os.PathLike object, not NoneType
【INFO】2024-11-26 07:44:25,016 - cloudlinkmonitor - We.Bare.Bears.S03E09.NORDiC.ENG.1080p.WEB.H264.DDP2.0-DERMAGiC.mkv 识别为：电视剧 咱们裸熊 (2015)
【INFO】2024-11-26 07:44:25,006 - themoviedb - We Bare Bears TMDB识别结果：电视剧 咱们裸熊 (2015) 63401
【INFO】2024-11-26 07:44:24,970 - themoviedb - We Bare Bears 使用TMDB识别缓存：咱们裸熊
【ERROR】2024-11-26 07:16:49,736 - cloudlinkmonitor - 文件转移模块运行失败

**Comment by thsrite** [comment]
v2.5.5 更新试试
