### ISSUE TITLE
下载器文件同步插件报错

### ISSUE THREAD

**Issue by 389377616** [thsrite/MoviePilot-Plugins#59]
【ERROR】2024-06-22 00:49:06,322 - scheduler.py - 定时任务 同步下载器文件记录服务 执行失败：list index out of range - Traceback (most recent call last):
请问这个报错是什么意思？要怎么处理

**Comment by 389377616** [comment]
【INFO】2024-06-23 05:38:09,997 - command.py - 处理事件：system.error - []

IndexError: list index out of range
                                                      ~~~~~~~~~^^^
    download_dir = download_dir.replace(sub_paths[0], sub_paths[1]).replace('\\', '/')
  File "/app/app/plugins/syncdownloadfiles/__init__.py", line 148, in sync
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 370, in start
【ERROR】2024-06-23 05:38:09,988 - scheduler.py - 定时任务 同步下载器文件记录服务 执行失败：list index out of range - Traceback (most recent call last):

**Comment by 389377616** [comment]
还是有错误提示

**Comment by 389377616** [comment]
> 看好路径配置

![Quicker_20240625_055242](https://github.com/thsrite/MoviePilot-Plugins/assets/52220248/fde6853c-40d8-4ff0-8f34-76f1c78516a0)
看什么路径？
