### ISSUE TITLE
实时软链接，突然，出错软链接，名字都错了，不是丢失中文，就是只剩数字，CD2挂载的阿里云软链接到本地磁盘

### ISSUE THREAD

**Issue by jinhua523** [thsrite/MoviePilot-Plugins#61]
0 

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/外语电影/一天\\ \\(2011\\)/一天.2011.1080p.BluRay-FRDS.nfo'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:44,643 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/外语电影/一天\\ \\(2011\\)/一天.2011.1080p.BluRay-FRDS.nfo' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:44,641 - filesoftlink - 创建媒体文件软连接 /volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/外语电影/一天\ \(2011\)/一天.2011.1080p.BluRay-FRDS.mkv 到 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/.2011.1080p.BluRay-FRDS.mkv 0 
【INFO】2024-06-23 12:01:44,615 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/thumb.jpg 已存在
【INFO】2024-06-23 12:01:44,614 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/poster.jpg 已存在
【INFO】2024-06-23 12:01:44,614 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/logo.png 已存在
【INFO】2024-06-23 12:01:44,613 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/disc.png 已存在
【INFO】2024-06-23 12:01:44,612 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/clearart.png 已存在
【INFO】2024-06-23 12:01:44,612 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/banner.jpg 已存在
【INFO】2024-06-23 12:01:44,611 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/background.jpg 已存在
【INFO】2024-06-23 12:01:44,610 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/一天 (2011)/backdrop.jpg 已存在
【INFO】2024-06-23 12:01:44,506 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/thumb.jpg 已存在
【INFO】2024-06-23 12:01:44,505 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/poster.jpg 已存在
【INFO】2024-06-23 12:01:44,504 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/logo.png 已存在
【INFO】2024-06-23 12:01:44,504 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/fanart.jpg 已存在
【INFO】2024-06-23 12:01:44,503 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/disc.png 已存在
【INFO】2024-06-23 12:01:44,502 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/clearart.png 已存在
【INFO】2024-06-23 12:01:44,502 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/banner.jpg 已存在
【INFO】2024-06-23 12:01:44,501 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/background.jpg 已存在
【INFO】2024-06-23 12:01:44,500 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/backdrop.jpg 已存在
【INFO】2024-06-23 12:01:44,499 - filesoftlink - 创建媒体文件软连接 /volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/外语电影/AI创世者\ \(2023\)/AI创世者.2023.2160p-CHDWEB.mkv 到 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/外语电影/AI创世者 (2023)/AI.2023.2160p-CHDWEB.mkv 0

**Comment by jinhua523** [comment]
【ERROR】2024-06-23 12:01:44,499 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/外语电影/AI创世者\\ \\(2023\\)/AI创世者\\ \\(2023\\)\\ -\\ 2160p\\ [CHDWEB].nfo' - Traceback (most recent call last):

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙的传人\\ \\(1991\\)/龙的传人.1991.nfo'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:44,155 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙的传人\\ \\(1991\\)/龙的传人.1991.nfo' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:44,153 - filesoftlink - 创建媒体文件软连接 /volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙的传人\ \(1991\)/龙的传人.1991.mkv 到 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙的传人 (1991)/.1991.mkv 0 

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙的传人\\ \\(1991\\)/龙的传人.1991.ass'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:44,152 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙的传人\\ \\(1991\\)/龙的传人.1991.ass' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:44,151 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙的传人 (1991)/poster.jpg 已存在
【INFO】2024-06-23 12:01:44,150 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙的传人 (1991)/backdrop.jpg 已存在

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙在天涯\\ \\(1989\\)/龙在天涯.1989.nfo'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:44,048 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙在天涯\\ \\(1989\\)/龙在天涯.1989.nfo' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:44,047 - filesoftlink - 创建媒体文件软连接 /volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙在天涯\ \(1989\)/龙在天涯.1989.mkv 到 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙在天涯 (1989)/.1989.mkv 0 

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙在天涯\\ \\(1989\\)/龙在天涯.1989.ass'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:44,046 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙在天涯\\ \\(1989\\)/龙在天涯.1989.ass' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:44,045 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙在天涯 (1989)/poster.jpg 已存在
【INFO】2024-06-23 12:01:44,044 - filesoftlink - 目标文件 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙在天涯 (1989)/backdrop.jpg 已存在

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙凤茶楼\\ \\(1990\\)/龙凤茶楼.1990.nfo'
         ^^^^^^^^^^^^^^^
    with open(src, 'rb') as fsrc:
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 436, in copy2
    shutil.copy2(str(file_path), target_file)
  File "/app/app/plugins/filesoftlink/__init__.py", line 358, in __handle_file
【ERROR】2024-06-23 12:01:43,938 - filesoftlink - 软连接发生错误：[Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙凤茶楼\\ \\(1990\\)/龙凤茶楼.1990.nfo' - Traceback (most recent call last):
【INFO】2024-06-23 12:01:43,937 - filesoftlink - 创建媒体文件软连接 /volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙凤茶楼\ \(1990\)/龙凤茶楼.1990.mkv 到 /volume1/NASTOOL/CD2/LINK/aliyun/个人影视/电影/华语电影/龙凤茶楼 (1990)/.1990.mkv 0 

FileNotFoundError: [Errno 2] No such file or directory: '/volume1/NASTOOL/CD2/CLOUD/aliyun/个人影视/电影/华语电影/龙凤茶楼\\ \\(1990\\)/龙凤茶楼.1990.ass'  原本：龙凤茶楼.1990.mkv 软链接之后变成.1990.mkv 中文没了，这是咋回事
